/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SolicitarDemoRouteImport } from './routes/solicitar-demo'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedPlataformaRouteImport } from './routes/_authenticated/plataforma'
import { Route as ClubBusinessSlugRouteImport } from './routes/club.$businessSlug'
import { Route as LegalDocumentRouteImport } from './routes/legal.$document'
import { Route as MiTarjetaPublicIdRouteImport } from './routes/mi-tarjeta.$publicId'
import { Route as AuthenticatedPanelIndexRouteImport } from './routes/_authenticated/panel.index'
import { Route as AuthenticatedPanelActividadRouteImport } from './routes/_authenticated/panel.actividad'
import { Route as AuthenticatedPanelAutomatizacionesRouteImport } from './routes/_authenticated/panel.automatizaciones'
import { Route as AuthenticatedPanelBeneficiosRouteImport } from './routes/_authenticated/panel.beneficios'
import { Route as AuthenticatedPanelCajaRouteImport } from './routes/_authenticated/panel.caja'
import { Route as AuthenticatedPanelCampanasRouteImport } from './routes/_authenticated/panel.campanas'
import { Route as AuthenticatedPanelCaptacionRouteImport } from './routes/_authenticated/panel.captacion'
import { Route as AuthenticatedPanelConfiguracionRouteImport } from './routes/_authenticated/panel.configuracion'
import { Route as AuthenticatedPanelEquipoRouteImport } from './routes/_authenticated/panel.equipo'
import { Route as AuthenticatedPanelEstablecimientosRouteImport } from './routes/_authenticated/panel.establecimientos'
import { Route as AuthenticatedPanelEstadisticasRouteImport } from './routes/_authenticated/panel.estadisticas'
import { Route as AuthenticatedPanelNotificacionesRouteImport } from './routes/_authenticated/panel.notificaciones'
import { Route as AuthenticatedPanelOnboardingRouteImport } from './routes/_authenticated/panel.onboarding'
import { Route as AuthenticatedPanelPerfilRouteImport } from './routes/_authenticated/panel.perfil'
import { Route as AuthenticatedPanelProgramaRouteImport } from './routes/_authenticated/panel.programa'
import { Route as AuthenticatedPanelRecompensasRouteImport } from './routes/_authenticated/panel.recompensas'
import { Route as AuthenticatedPanelTiendaRouteImport } from './routes/_authenticated/panel.tienda'
import { Route as AuthenticatedPanelWalletRouteImport } from './routes/_authenticated/panel.wallet'
import { Route as UnirmeOrganizationSlugIndexRouteImport } from './routes/unirme.$organizationSlug.index'
import { Route as UnirmeOrganizationSlugLocationSlugRouteImport } from './routes/unirme.$organizationSlug.$locationSlug'
import { Route as AuthenticatedPanelClientesIndexRouteImport } from './routes/_authenticated/panel.clientes.index'
import { Route as AuthenticatedPanelClientesMembershipIdRouteImport } from './routes/_authenticated/panel.clientes.$membershipId'
import { Route as ClubBusinessSlugLegalDocumentRouteImport } from './routes/club.$businessSlug.legal.$document'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarDemoRoute = SolicitarDemoRouteImport.update({
  id: '/solicitar-demo',
  path: '/solicitar-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlataformaRoute = AuthenticatedPlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClubBusinessSlugRoute = ClubBusinessSlugRouteImport.update({
  id: '/club/$businessSlug',
  path: '/club/$businessSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocumentRoute = LegalDocumentRouteImport.update({
  id: '/legal/$document',
  path: '/legal/$document',
  getParentRoute: () => rootRouteImport,
} as any)
const MiTarjetaPublicIdRoute = MiTarjetaPublicIdRouteImport.update({
  id: '/mi-tarjeta/$publicId',
  path: '/mi-tarjeta/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelIndexRoute = AuthenticatedPanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPanelRoute,
} as any)
const AuthenticatedPanelActividadRoute =
  AuthenticatedPanelActividadRouteImport.update({
    id: '/actividad',
    path: '/actividad',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelAutomatizacionesRoute =
  AuthenticatedPanelAutomatizacionesRouteImport.update({
    id: '/automatizaciones',
    path: '/automatizaciones',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelBeneficiosRoute =
  AuthenticatedPanelBeneficiosRouteImport.update({
    id: '/beneficios',
    path: '/beneficios',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelCajaRoute = AuthenticatedPanelCajaRouteImport.update({
  id: '/caja',
  path: '/caja',
  getParentRoute: () => AuthenticatedPanelRoute,
} as any)
const AuthenticatedPanelCampanasRoute =
  AuthenticatedPanelCampanasRouteImport.update({
    id: '/campanas',
    path: '/campanas',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelCaptacionRoute =
  AuthenticatedPanelCaptacionRouteImport.update({
    id: '/captacion',
    path: '/captacion',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelConfiguracionRoute =
  AuthenticatedPanelConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelEquipoRoute =
  AuthenticatedPanelEquipoRouteImport.update({
    id: '/equipo',
    path: '/equipo',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelEstablecimientosRoute =
  AuthenticatedPanelEstablecimientosRouteImport.update({
    id: '/establecimientos',
    path: '/establecimientos',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelEstadisticasRoute =
  AuthenticatedPanelEstadisticasRouteImport.update({
    id: '/estadisticas',
    path: '/estadisticas',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelNotificacionesRoute =
  AuthenticatedPanelNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelOnboardingRoute =
  AuthenticatedPanelOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelPerfilRoute =
  AuthenticatedPanelPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelProgramaRoute =
  AuthenticatedPanelProgramaRouteImport.update({
    id: '/programa',
    path: '/programa',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelRecompensasRoute =
  AuthenticatedPanelRecompensasRouteImport.update({
    id: '/recompensas',
    path: '/recompensas',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelTiendaRoute =
  AuthenticatedPanelTiendaRouteImport.update({
    id: '/tienda',
    path: '/tienda',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelWalletRoute =
  AuthenticatedPanelWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const UnirmeOrganizationSlugIndexRoute =
  UnirmeOrganizationSlugIndexRouteImport.update({
    id: '/unirme/$organizationSlug/',
    path: '/unirme/$organizationSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UnirmeOrganizationSlugLocationSlugRoute =
  UnirmeOrganizationSlugLocationSlugRouteImport.update({
    id: '/unirme/$organizationSlug/$locationSlug',
    path: '/unirme/$organizationSlug/$locationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPanelClientesIndexRoute =
  AuthenticatedPanelClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const AuthenticatedPanelClientesMembershipIdRoute =
  AuthenticatedPanelClientesMembershipIdRouteImport.update({
    id: '/clientes/$membershipId',
    path: '/clientes/$membershipId',
    getParentRoute: () => AuthenticatedPanelRoute,
  } as any)
const ClubBusinessSlugLegalDocumentRoute =
  ClubBusinessSlugLegalDocumentRouteImport.update({
    id: '/legal/$document',
    path: '/legal/$document',
    getParentRoute: () => ClubBusinessSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/solicitar-demo': typeof SolicitarDemoRoute
  '/panel': typeof AuthenticatedPanelRouteWithChildren
  '/plataforma': typeof AuthenticatedPlataformaRoute
  '/club/$businessSlug': typeof ClubBusinessSlugRouteWithChildren
  '/legal/$document': typeof LegalDocumentRoute
  '/mi-tarjeta/$publicId': typeof MiTarjetaPublicIdRoute
  '/panel/actividad': typeof AuthenticatedPanelActividadRoute
  '/panel/automatizaciones': typeof AuthenticatedPanelAutomatizacionesRoute
  '/panel/beneficios': typeof AuthenticatedPanelBeneficiosRoute
  '/panel/caja': typeof AuthenticatedPanelCajaRoute
  '/panel/campanas': typeof AuthenticatedPanelCampanasRoute
  '/panel/captacion': typeof AuthenticatedPanelCaptacionRoute
  '/panel/configuracion': typeof AuthenticatedPanelConfiguracionRoute
  '/panel/equipo': typeof AuthenticatedPanelEquipoRoute
  '/panel/establecimientos': typeof AuthenticatedPanelEstablecimientosRoute
  '/panel/estadisticas': typeof AuthenticatedPanelEstadisticasRoute
  '/panel/notificaciones': typeof AuthenticatedPanelNotificacionesRoute
  '/panel/onboarding': typeof AuthenticatedPanelOnboardingRoute
  '/panel/perfil': typeof AuthenticatedPanelPerfilRoute
  '/panel/programa': typeof AuthenticatedPanelProgramaRoute
  '/panel/recompensas': typeof AuthenticatedPanelRecompensasRoute
  '/panel/tienda': typeof AuthenticatedPanelTiendaRoute
  '/panel/wallet': typeof AuthenticatedPanelWalletRoute
  '/unirme/$organizationSlug/$locationSlug': typeof UnirmeOrganizationSlugLocationSlugRoute
  '/panel/': typeof AuthenticatedPanelIndexRoute
  '/unirme/$organizationSlug/': typeof UnirmeOrganizationSlugIndexRoute
  '/panel/clientes/$membershipId': typeof AuthenticatedPanelClientesMembershipIdRoute
  '/club/$businessSlug/legal/$document': typeof ClubBusinessSlugLegalDocumentRoute
  '/panel/clientes/': typeof AuthenticatedPanelClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/solicitar-demo': typeof SolicitarDemoRoute
  '/plataforma': typeof AuthenticatedPlataformaRoute
  '/club/$businessSlug': typeof ClubBusinessSlugRouteWithChildren
  '/legal/$document': typeof LegalDocumentRoute
  '/mi-tarjeta/$publicId': typeof MiTarjetaPublicIdRoute
  '/panel/actividad': typeof AuthenticatedPanelActividadRoute
  '/panel/automatizaciones': typeof AuthenticatedPanelAutomatizacionesRoute
  '/panel/beneficios': typeof AuthenticatedPanelBeneficiosRoute
  '/panel/caja': typeof AuthenticatedPanelCajaRoute
  '/panel/campanas': typeof AuthenticatedPanelCampanasRoute
  '/panel/captacion': typeof AuthenticatedPanelCaptacionRoute
  '/panel/configuracion': typeof AuthenticatedPanelConfiguracionRoute
  '/panel/equipo': typeof AuthenticatedPanelEquipoRoute
  '/panel/establecimientos': typeof AuthenticatedPanelEstablecimientosRoute
  '/panel/estadisticas': typeof AuthenticatedPanelEstadisticasRoute
  '/panel/notificaciones': typeof AuthenticatedPanelNotificacionesRoute
  '/panel/onboarding': typeof AuthenticatedPanelOnboardingRoute
  '/panel/perfil': typeof AuthenticatedPanelPerfilRoute
  '/panel/programa': typeof AuthenticatedPanelProgramaRoute
  '/panel/recompensas': typeof AuthenticatedPanelRecompensasRoute
  '/panel/tienda': typeof AuthenticatedPanelTiendaRoute
  '/panel/wallet': typeof AuthenticatedPanelWalletRoute
  '/unirme/$organizationSlug/$locationSlug': typeof UnirmeOrganizationSlugLocationSlugRoute
  '/panel': typeof AuthenticatedPanelIndexRoute
  '/unirme/$organizationSlug': typeof UnirmeOrganizationSlugIndexRoute
  '/panel/clientes/$membershipId': typeof AuthenticatedPanelClientesMembershipIdRoute
  '/club/$businessSlug/legal/$document': typeof ClubBusinessSlugLegalDocumentRoute
  '/panel/clientes': typeof AuthenticatedPanelClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/solicitar-demo': typeof SolicitarDemoRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRouteWithChildren
  '/_authenticated/plataforma': typeof AuthenticatedPlataformaRoute
  '/club/$businessSlug': typeof ClubBusinessSlugRouteWithChildren
  '/legal/$document': typeof LegalDocumentRoute
  '/mi-tarjeta/$publicId': typeof MiTarjetaPublicIdRoute
  '/_authenticated/panel/actividad': typeof AuthenticatedPanelActividadRoute
  '/_authenticated/panel/automatizaciones': typeof AuthenticatedPanelAutomatizacionesRoute
  '/_authenticated/panel/beneficios': typeof AuthenticatedPanelBeneficiosRoute
  '/_authenticated/panel/caja': typeof AuthenticatedPanelCajaRoute
  '/_authenticated/panel/campanas': typeof AuthenticatedPanelCampanasRoute
  '/_authenticated/panel/captacion': typeof AuthenticatedPanelCaptacionRoute
  '/_authenticated/panel/configuracion': typeof AuthenticatedPanelConfiguracionRoute
  '/_authenticated/panel/equipo': typeof AuthenticatedPanelEquipoRoute
  '/_authenticated/panel/establecimientos': typeof AuthenticatedPanelEstablecimientosRoute
  '/_authenticated/panel/estadisticas': typeof AuthenticatedPanelEstadisticasRoute
  '/_authenticated/panel/notificaciones': typeof AuthenticatedPanelNotificacionesRoute
  '/_authenticated/panel/onboarding': typeof AuthenticatedPanelOnboardingRoute
  '/_authenticated/panel/perfil': typeof AuthenticatedPanelPerfilRoute
  '/_authenticated/panel/programa': typeof AuthenticatedPanelProgramaRoute
  '/_authenticated/panel/recompensas': typeof AuthenticatedPanelRecompensasRoute
  '/_authenticated/panel/tienda': typeof AuthenticatedPanelTiendaRoute
  '/_authenticated/panel/wallet': typeof AuthenticatedPanelWalletRoute
  '/unirme/$organizationSlug/$locationSlug': typeof UnirmeOrganizationSlugLocationSlugRoute
  '/_authenticated/panel/': typeof AuthenticatedPanelIndexRoute
  '/unirme/$organizationSlug/': typeof UnirmeOrganizationSlugIndexRoute
  '/_authenticated/panel/clientes/$membershipId': typeof AuthenticatedPanelClientesMembershipIdRoute
  '/club/$businessSlug/legal/$document': typeof ClubBusinessSlugLegalDocumentRoute
  '/_authenticated/panel/clientes/': typeof AuthenticatedPanelClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/solicitar-demo'
    | '/panel'
    | '/plataforma'
    | '/club/$businessSlug'
    | '/legal/$document'
    | '/mi-tarjeta/$publicId'
    | '/panel/actividad'
    | '/panel/automatizaciones'
    | '/panel/beneficios'
    | '/panel/caja'
    | '/panel/campanas'
    | '/panel/captacion'
    | '/panel/configuracion'
    | '/panel/equipo'
    | '/panel/establecimientos'
    | '/panel/estadisticas'
    | '/panel/notificaciones'
    | '/panel/onboarding'
    | '/panel/perfil'
    | '/panel/programa'
    | '/panel/recompensas'
    | '/panel/tienda'
    | '/panel/wallet'
    | '/unirme/$organizationSlug/$locationSlug'
    | '/panel/'
    | '/unirme/$organizationSlug/'
    | '/panel/clientes/$membershipId'
    | '/club/$businessSlug/legal/$document'
    | '/panel/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/solicitar-demo'
    | '/plataforma'
    | '/club/$businessSlug'
    | '/legal/$document'
    | '/mi-tarjeta/$publicId'
    | '/panel/actividad'
    | '/panel/automatizaciones'
    | '/panel/beneficios'
    | '/panel/caja'
    | '/panel/campanas'
    | '/panel/captacion'
    | '/panel/configuracion'
    | '/panel/equipo'
    | '/panel/establecimientos'
    | '/panel/estadisticas'
    | '/panel/notificaciones'
    | '/panel/onboarding'
    | '/panel/perfil'
    | '/panel/programa'
    | '/panel/recompensas'
    | '/panel/tienda'
    | '/panel/wallet'
    | '/unirme/$organizationSlug/$locationSlug'
    | '/panel'
    | '/unirme/$organizationSlug'
    | '/panel/clientes/$membershipId'
    | '/club/$businessSlug/legal/$document'
    | '/panel/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/solicitar-demo'
    | '/_authenticated/panel'
    | '/_authenticated/plataforma'
    | '/club/$businessSlug'
    | '/legal/$document'
    | '/mi-tarjeta/$publicId'
    | '/_authenticated/panel/actividad'
    | '/_authenticated/panel/automatizaciones'
    | '/_authenticated/panel/beneficios'
    | '/_authenticated/panel/caja'
    | '/_authenticated/panel/campanas'
    | '/_authenticated/panel/captacion'
    | '/_authenticated/panel/configuracion'
    | '/_authenticated/panel/equipo'
    | '/_authenticated/panel/establecimientos'
    | '/_authenticated/panel/estadisticas'
    | '/_authenticated/panel/notificaciones'
    | '/_authenticated/panel/onboarding'
    | '/_authenticated/panel/perfil'
    | '/_authenticated/panel/programa'
    | '/_authenticated/panel/recompensas'
    | '/_authenticated/panel/tienda'
    | '/_authenticated/panel/wallet'
    | '/unirme/$organizationSlug/$locationSlug'
    | '/_authenticated/panel/'
    | '/unirme/$organizationSlug/'
    | '/_authenticated/panel/clientes/$membershipId'
    | '/club/$businessSlug/legal/$document'
    | '/_authenticated/panel/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SolicitarDemoRoute: typeof SolicitarDemoRoute
  ClubBusinessSlugRoute: typeof ClubBusinessSlugRouteWithChildren
  LegalDocumentRoute: typeof LegalDocumentRoute
  MiTarjetaPublicIdRoute: typeof MiTarjetaPublicIdRoute
  UnirmeOrganizationSlugLocationSlugRoute: typeof UnirmeOrganizationSlugLocationSlugRoute
  UnirmeOrganizationSlugIndexRoute: typeof UnirmeOrganizationSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitar-demo': {
      id: '/solicitar-demo'
      path: '/solicitar-demo'
      fullPath: '/solicitar-demo'
      preLoaderRoute: typeof SolicitarDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plataforma': {
      id: '/_authenticated/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof AuthenticatedPlataformaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/club/$businessSlug': {
      id: '/club/$businessSlug'
      path: '/club/$businessSlug'
      fullPath: '/club/$businessSlug'
      preLoaderRoute: typeof ClubBusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$document': {
      id: '/legal/$document'
      path: '/legal/$document'
      fullPath: '/legal/$document'
      preLoaderRoute: typeof LegalDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-tarjeta/$publicId': {
      id: '/mi-tarjeta/$publicId'
      path: '/mi-tarjeta/$publicId'
      fullPath: '/mi-tarjeta/$publicId'
      preLoaderRoute: typeof MiTarjetaPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel/': {
      id: '/_authenticated/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof AuthenticatedPanelIndexRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/actividad': {
      id: '/_authenticated/panel/actividad'
      path: '/actividad'
      fullPath: '/panel/actividad'
      preLoaderRoute: typeof AuthenticatedPanelActividadRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/automatizaciones': {
      id: '/_authenticated/panel/automatizaciones'
      path: '/automatizaciones'
      fullPath: '/panel/automatizaciones'
      preLoaderRoute: typeof AuthenticatedPanelAutomatizacionesRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/beneficios': {
      id: '/_authenticated/panel/beneficios'
      path: '/beneficios'
      fullPath: '/panel/beneficios'
      preLoaderRoute: typeof AuthenticatedPanelBeneficiosRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/caja': {
      id: '/_authenticated/panel/caja'
      path: '/caja'
      fullPath: '/panel/caja'
      preLoaderRoute: typeof AuthenticatedPanelCajaRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/campanas': {
      id: '/_authenticated/panel/campanas'
      path: '/campanas'
      fullPath: '/panel/campanas'
      preLoaderRoute: typeof AuthenticatedPanelCampanasRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/captacion': {
      id: '/_authenticated/panel/captacion'
      path: '/captacion'
      fullPath: '/panel/captacion'
      preLoaderRoute: typeof AuthenticatedPanelCaptacionRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/configuracion': {
      id: '/_authenticated/panel/configuracion'
      path: '/configuracion'
      fullPath: '/panel/configuracion'
      preLoaderRoute: typeof AuthenticatedPanelConfiguracionRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/equipo': {
      id: '/_authenticated/panel/equipo'
      path: '/equipo'
      fullPath: '/panel/equipo'
      preLoaderRoute: typeof AuthenticatedPanelEquipoRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/establecimientos': {
      id: '/_authenticated/panel/establecimientos'
      path: '/establecimientos'
      fullPath: '/panel/establecimientos'
      preLoaderRoute: typeof AuthenticatedPanelEstablecimientosRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/estadisticas': {
      id: '/_authenticated/panel/estadisticas'
      path: '/estadisticas'
      fullPath: '/panel/estadisticas'
      preLoaderRoute: typeof AuthenticatedPanelEstadisticasRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/notificaciones': {
      id: '/_authenticated/panel/notificaciones'
      path: '/notificaciones'
      fullPath: '/panel/notificaciones'
      preLoaderRoute: typeof AuthenticatedPanelNotificacionesRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/onboarding': {
      id: '/_authenticated/panel/onboarding'
      path: '/onboarding'
      fullPath: '/panel/onboarding'
      preLoaderRoute: typeof AuthenticatedPanelOnboardingRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/perfil': {
      id: '/_authenticated/panel/perfil'
      path: '/perfil'
      fullPath: '/panel/perfil'
      preLoaderRoute: typeof AuthenticatedPanelPerfilRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/programa': {
      id: '/_authenticated/panel/programa'
      path: '/programa'
      fullPath: '/panel/programa'
      preLoaderRoute: typeof AuthenticatedPanelProgramaRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/recompensas': {
      id: '/_authenticated/panel/recompensas'
      path: '/recompensas'
      fullPath: '/panel/recompensas'
      preLoaderRoute: typeof AuthenticatedPanelRecompensasRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/tienda': {
      id: '/_authenticated/panel/tienda'
      path: '/tienda'
      fullPath: '/panel/tienda'
      preLoaderRoute: typeof AuthenticatedPanelTiendaRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/wallet': {
      id: '/_authenticated/panel/wallet'
      path: '/wallet'
      fullPath: '/panel/wallet'
      preLoaderRoute: typeof AuthenticatedPanelWalletRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/unirme/$organizationSlug/': {
      id: '/unirme/$organizationSlug/'
      path: '/unirme/$organizationSlug'
      fullPath: '/unirme/$organizationSlug/'
      preLoaderRoute: typeof UnirmeOrganizationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unirme/$organizationSlug/$locationSlug': {
      id: '/unirme/$organizationSlug/$locationSlug'
      path: '/unirme/$organizationSlug/$locationSlug'
      fullPath: '/unirme/$organizationSlug/$locationSlug'
      preLoaderRoute: typeof UnirmeOrganizationSlugLocationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel/clientes/': {
      id: '/_authenticated/panel/clientes/'
      path: '/clientes'
      fullPath: '/panel/clientes/'
      preLoaderRoute: typeof AuthenticatedPanelClientesIndexRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/_authenticated/panel/clientes/$membershipId': {
      id: '/_authenticated/panel/clientes/$membershipId'
      path: '/clientes/$membershipId'
      fullPath: '/panel/clientes/$membershipId'
      preLoaderRoute: typeof AuthenticatedPanelClientesMembershipIdRouteImport
      parentRoute: typeof AuthenticatedPanelRoute
    }
    '/club/$businessSlug/legal/$document': {
      id: '/club/$businessSlug/legal/$document'
      path: '/legal/$document'
      fullPath: '/club/$businessSlug/legal/$document'
      preLoaderRoute: typeof ClubBusinessSlugLegalDocumentRouteImport
      parentRoute: typeof ClubBusinessSlugRoute
    }
  }
}

interface AuthenticatedPanelRouteChildren {
  AuthenticatedPanelActividadRoute: typeof AuthenticatedPanelActividadRoute
  AuthenticatedPanelAutomatizacionesRoute: typeof AuthenticatedPanelAutomatizacionesRoute
  AuthenticatedPanelBeneficiosRoute: typeof AuthenticatedPanelBeneficiosRoute
  AuthenticatedPanelCajaRoute: typeof AuthenticatedPanelCajaRoute
  AuthenticatedPanelCampanasRoute: typeof AuthenticatedPanelCampanasRoute
  AuthenticatedPanelCaptacionRoute: typeof AuthenticatedPanelCaptacionRoute
  AuthenticatedPanelConfiguracionRoute: typeof AuthenticatedPanelConfiguracionRoute
  AuthenticatedPanelEquipoRoute: typeof AuthenticatedPanelEquipoRoute
  AuthenticatedPanelEstablecimientosRoute: typeof AuthenticatedPanelEstablecimientosRoute
  AuthenticatedPanelEstadisticasRoute: typeof AuthenticatedPanelEstadisticasRoute
  AuthenticatedPanelNotificacionesRoute: typeof AuthenticatedPanelNotificacionesRoute
  AuthenticatedPanelOnboardingRoute: typeof AuthenticatedPanelOnboardingRoute
  AuthenticatedPanelPerfilRoute: typeof AuthenticatedPanelPerfilRoute
  AuthenticatedPanelProgramaRoute: typeof AuthenticatedPanelProgramaRoute
  AuthenticatedPanelRecompensasRoute: typeof AuthenticatedPanelRecompensasRoute
  AuthenticatedPanelTiendaRoute: typeof AuthenticatedPanelTiendaRoute
  AuthenticatedPanelWalletRoute: typeof AuthenticatedPanelWalletRoute
  AuthenticatedPanelIndexRoute: typeof AuthenticatedPanelIndexRoute
  AuthenticatedPanelClientesMembershipIdRoute: typeof AuthenticatedPanelClientesMembershipIdRoute
  AuthenticatedPanelClientesIndexRoute: typeof AuthenticatedPanelClientesIndexRoute
}

const AuthenticatedPanelRouteChildren: AuthenticatedPanelRouteChildren = {
  AuthenticatedPanelActividadRoute: AuthenticatedPanelActividadRoute,
  AuthenticatedPanelAutomatizacionesRoute:
    AuthenticatedPanelAutomatizacionesRoute,
  AuthenticatedPanelBeneficiosRoute: AuthenticatedPanelBeneficiosRoute,
  AuthenticatedPanelCajaRoute: AuthenticatedPanelCajaRoute,
  AuthenticatedPanelCampanasRoute: AuthenticatedPanelCampanasRoute,
  AuthenticatedPanelCaptacionRoute: AuthenticatedPanelCaptacionRoute,
  AuthenticatedPanelConfiguracionRoute: AuthenticatedPanelConfiguracionRoute,
  AuthenticatedPanelEquipoRoute: AuthenticatedPanelEquipoRoute,
  AuthenticatedPanelEstablecimientosRoute:
    AuthenticatedPanelEstablecimientosRoute,
  AuthenticatedPanelEstadisticasRoute: AuthenticatedPanelEstadisticasRoute,
  AuthenticatedPanelNotificacionesRoute: AuthenticatedPanelNotificacionesRoute,
  AuthenticatedPanelOnboardingRoute: AuthenticatedPanelOnboardingRoute,
  AuthenticatedPanelPerfilRoute: AuthenticatedPanelPerfilRoute,
  AuthenticatedPanelProgramaRoute: AuthenticatedPanelProgramaRoute,
  AuthenticatedPanelRecompensasRoute: AuthenticatedPanelRecompensasRoute,
  AuthenticatedPanelTiendaRoute: AuthenticatedPanelTiendaRoute,
  AuthenticatedPanelWalletRoute: AuthenticatedPanelWalletRoute,
  AuthenticatedPanelIndexRoute: AuthenticatedPanelIndexRoute,
  AuthenticatedPanelClientesMembershipIdRoute:
    AuthenticatedPanelClientesMembershipIdRoute,
  AuthenticatedPanelClientesIndexRoute: AuthenticatedPanelClientesIndexRoute,
}

const AuthenticatedPanelRouteWithChildren =
  AuthenticatedPanelRoute._addFileChildren(AuthenticatedPanelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRouteWithChildren
  AuthenticatedPlataformaRoute: typeof AuthenticatedPlataformaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPanelRoute: AuthenticatedPanelRouteWithChildren,
  AuthenticatedPlataformaRoute: AuthenticatedPlataformaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClubBusinessSlugRouteChildren {
  ClubBusinessSlugLegalDocumentRoute: typeof ClubBusinessSlugLegalDocumentRoute
}

const ClubBusinessSlugRouteChildren: ClubBusinessSlugRouteChildren = {
  ClubBusinessSlugLegalDocumentRoute: ClubBusinessSlugLegalDocumentRoute,
}

const ClubBusinessSlugRouteWithChildren =
  ClubBusinessSlugRoute._addFileChildren(ClubBusinessSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SolicitarDemoRoute: SolicitarDemoRoute,
  ClubBusinessSlugRoute: ClubBusinessSlugRouteWithChildren,
  LegalDocumentRoute: LegalDocumentRoute,
  MiTarjetaPublicIdRoute: MiTarjetaPublicIdRoute,
  UnirmeOrganizationSlugLocationSlugRoute:
    UnirmeOrganizationSlugLocationSlugRoute,
  UnirmeOrganizationSlugIndexRoute: UnirmeOrganizationSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
